import type { Spark } from '../types';

/* ============================================================================
   heatt — the house notes.

   Short-form posts written by @heatt: release notes, design decisions, and
   things worth saying out loud. No invented characters, no fake crowds.
   ==========================================================================*/

export const SPARKS: Spark[] = [
  {
    id: 'ht-note-heat',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-23T09:20:00Z',
    reactions: 412,
    comments: 38,
    reposts: 96,
    text: 'How heat works, in one line: **tap** to heat something, **hold** to mean it.\n\nHold long enough and the piece ignites. There is no score, no leaderboard, no profile rank. Heat is a note you leave on a piece of writing — not a number you carry around.',
    tags: ['meta', 'heat'],
  },
  {
    id: 'ht-note-share',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-22T18:04:00Z',
    reactions: 268,
    comments: 21,
    reposts: 74,
    text: 'A share should look like something you would actually send someone.\n\nSo the share studio draws the poster at real size — 1080×1920 for stories, 1080×1080 for feeds — with the line you chose, your name, and the piece it came from. Preview and export are the same pixels.',
    tags: ['sharing', 'design'],
    media: [{ url: '/art/story-canvas.jpg', alt: 'A story poster laid out on a dark surface' }],
  },
  {
    id: 'ht-note-shelf',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-21T07:31:00Z',
    reactions: 195,
    comments: 14,
    reposts: 41,
    text: 'Your library is the only place in this app that keeps score — and it keeps score of one thing: what you chose to come back to.',
    tags: ['reading'],
  },
  {
    id: 'ht-note-reading',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-19T16:12:00Z',
    reactions: 233,
    comments: 19,
    reposts: 52,
    text: 'Long-form opens in the same room. No tabs, no redirect, no "continue on the publisher\'s site".\n\nA thin progress bar floats over whatever you are doing and remembers where you stopped.',
    tags: ['reading', 'design'],
  },
  {
    id: 'ht-note-syndication',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-17T11:45:00Z',
    reactions: 142,
    comments: 11,
    reposts: 28,
    text: 'Everything under "From the wire" is written by a real person and credited to their real handle, with the canonical link kept intact. We index public writing; we do not rewrite it and we do not invent authors.',
    tags: ['meta', 'wire'],
    link: {
      url: 'https://dev.to',
      title: 'Forem — where programmers share ideas',
      site: 'dev.to',
      desc: 'The public API behind the wire: real authors, real counters, canonical URLs.',
    },
  },
  {
    id: 'ht-note-dark',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-15T20:02:00Z',
    reactions: 306,
    comments: 27,
    reposts: 88,
    text: 'A dark interface is not a black background with white text. It is a light model: five close-together greys, one lit edge per surface, and exactly one accent reserved for things that are actually happening.',
    tags: ['design', 'colour'],
    media: [{ url: '/art/nocturne-ui.jpg', alt: 'A dark interface lit by a single warm surface' }],
  },
  {
    id: 'ht-note-removed',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-13T08:20:00Z',
    reactions: 174,
    comments: 22,
    reposts: 39,
    text: 'We deleted the reading receipt, the temperature gauge, the thermal mass, and every label that made a piece of writing sound like a physics experiment.\n\nThe app got smaller and better.',
    tags: ['meta', 'design'],
  },
  {
    id: 'ht-note-motion',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-11T14:08:00Z',
    reactions: 221,
    comments: 16,
    reposts: 57,
    text: 'Motion rule we now follow everywhere: fewer movements, each one bigger, none of them repeated.\n\nAn interface that animates constantly is not alive — it is nervous.',
    tags: ['motion', 'design'],
  },
  {
    id: 'ht-note-typography',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-09T09:55:00Z',
    reactions: 258,
    comments: 18,
    reposts: 63,
    text: 'Reading type is a different job from interface type.\n\nInter for the chrome, Newsreader for the body, a 68-character measure, and 1.72 line-height. Everything else is decoration.',
    tags: ['typography', 'reading'],
  },
  {
    id: 'ht-note-links',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-06T17:40:00Z',
    reactions: 119,
    comments: 9,
    reposts: 24,
    text: 'A link is a sentence, not a leak. Every link in a note gets a real preview card — title, site, one line of description — so you know what you are about to open before you leave the room.',
    tags: ['product'],
  },
  {
    id: 'ht-note-house',
    kind: 'spark',
    author: 'heatt',
    date: '2026-09-03T12:00:00Z',
    reactions: 331,
    comments: 44,
    reposts: 102,
    text: 'Every piece here is either written by the house, syndicated from a real writer, or written by you.\n\nWe would rather show you an honest empty shelf than a wall of imaginary people.',
    tags: ['meta'],
    poll: {
      question: 'What should the house write next?',
      options: [
        { label: 'How the wire is curated', votes: 184 },
        { label: 'The share studio, end to end', votes: 236 },
        { label: 'Why there is no algorithm', votes: 301 },
        { label: 'A reading guide for the dark', votes: 158 },
      ],
    },
  },
  {
    id: 'ht-note-keep',
    kind: 'spark',
    author: 'heatt',
    date: '2026-08-30T07:12:00Z',
    reactions: 156,
    comments: 12,
    reposts: 31,
    text: 'Save it now, read it on the train. The keeper is one tap on any card, and it survives a refresh, a reboot and a bad connection.',
    tags: ['reading', 'product'],
  },
];
